### ISSUE TITLE
For a given lambda_obs, eta is different for different data samples

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#80] opened 2017-03-21 08:34 UTC
The results for eta should be the same across forests since it only depends on the error of precision
calibration at a given wavelength.
In other words, eta is a function of lambdaOBS not of lambdaRF.

It is very stable between the MGII, SIIV and CIV forests. (first plot)

It is getting different for the Lya and the Lyb forests. (first plot)

Maybe this is linked to issue 48 (https://github.com/igmhub/pyLyA/issues/48) (third plot)

Anyway, this is not that important, but it would be nice to understand the reason.

Eta vs lambda_obs:
![eta_vs_lambda_obs](https://cloud.githubusercontent.com/assets/3166436/24138578/07361692-0e19-11e7-80e7-8f1f66d694b4.png)

sigmaLSS vs lambda_obs:
![sigmalss_vs_lambda_obs](https://cloud.githubusercontent.com/assets/3166436/24138579/07372b86-0e19-11e7-8fbc-544562bdc082.png)

flux vs lambda_obs:
![mean_flux_vs_lambda_obs](https://cloud.githubusercontent.com/assets/3166436/24138577/073460a4-0e19-11e7-8e74-7cbf467744bd.png)

flux vs lambda_RF:
![mean_flux_vs_lambda_rf](https://cloud.githubusercontent.com/assets/3166436/24138576/0731fecc-0e19-11e7-8c5a-c1d5f39ac675.png)

**Comment by andreufont** [comment] 2017-03-21 08:48
Eta is a way of describing extra variance as a correction of the noise variance, right?

If so, you could have extra variance in the spectra coming from other things, and you think you need to correct the noise variance when may be the noise was ok. 

For instance, think about continuum errors. If your model don't take these into account, you will measure some extra large variance, and you will hide under the rug (eta). 

It might be that what you are seeing is that different parts of the spectrum (in rest frame wavelength) have different amount of continuum errors.

**Comment by ngbusca** [comment] 2017-03-21 09:15
I disagree, eta is (intended to be) a correction for the noise miscalibration which is a function of lambda_obs. In your plot there's a very good match up to ~5500. I can't say there's a disagreement above since there are no errorbars.

**Comment by londumas** [comment] 2017-03-21 09:21
@andreufont I disagree with you, this effect should reflect more on sigma_pow2_LSS.

@ngbusca I agree with you, to see if what I see is significant, we should plot the error.
For now, the code doesn't give any, I will think on a cleaver way to get it and store it

**Comment by andreufont** [comment] 2017-03-21 09:21
May be I wasn't clear: I was not suggesting that the noise correction should depend on rest frame wavelength, this wouldn't make sense. I was suggesting that *if* there was a dependence of eta on the rest-frame range used, it could be explained by extra variance not present in your model, like for instance variance in the continuum.

**Comment by ngbusca** [comment] 2017-03-21 09:40
I agree with @andreufont , but note that a dependence of eta vs lambda_rf is expected since not all bins in lambda_rf correspond to the same mean lambda_obs. So one should look for an evolution with lambda_rf beyond what's expected from the known evolution with lambda_obs.

**Comment by ngbusca** [comment] 2017-10-20 15:20
@londumas Looking back at this issue, I don't understand what the problem is. eta was always a function of lambda_obs, no ?

**Comment by londumas** [comment] 2017-10-20 15:36
yes, but it shouldn't be of lambda_RF

**Comment by ngbusca** [comment] 2017-10-20 15:38
@londumas I agree... was it ever under discussion?

**Comment by londumas** [comment] 2017-10-20 15:39
@ngbusca , what do you mean ?

**Comment by ngbusca** [comment] 2017-10-20 15:41
@londumas the title of the issue is "eta is a function of lambdaRF". Eta was always a function of lambda_obs, and we all agree that's the way it should be. So what is this issue about?

**Comment by londumas** [comment] 2017-10-20 17:16
The title talks about "lambdaRF" not lambda_obs

**Comment by ngbusca** [comment] 2017-10-20 17:18
right, why does it talk about lambdaRF?

**Comment by londumas** [comment] 2017-10-20 17:20
do we agree that if eta takes care of errors of the pipeline it should only be a function of lambda_Obs ?
Not a function of lambda_RF ?
But the first plot shows that it is a function of lambda_RF since the blue and green and other curves are different.

**Comment by ngbusca** [comment] 2017-10-20 17:33
I disagree, they show that there's something we don't fully understand.

**Comment by ngbusca** [comment] 2017-10-20 17:34
for example, that the noise is more complicated than our simple model

**Comment by londumas** [comment] 2017-10-20 17:35
ok, so we agree. Our simple model is good but not good enough.
You think this isn't the place to try to solve this issue ?

**Comment by ngbusca** [comment] 2017-10-20 17:38
Let's keep it open, but I'll change the title to something that makes more sense.

**Comment by londumas** [comment] 2017-11-03 16:20
After the addition of the "fudge" term, the eta obtained in different forest are very similar.
The only difference seems to be a normalization for the MGII forest.
It would be interesting to know why.

![eta_lambdaobs](https://user-images.githubusercontent.com/3166436/32384376-59557d7c-c080-11e7-9170-285feedca170.png)

![sigma2lss_lambdaobs](https://user-images.githubusercontent.com/3166436/32384379-59f20b74-c080-11e7-9a48-6b2ccd41ed30.png)

![fudge_lambdaobs](https://user-images.githubusercontent.com/3166436/32384378-59b49c08-c080-11e7-94b0-d5713b0c79b7.png)

![flux_lambdarf](https://user-images.githubusercontent.com/3166436/32384377-59946492-c080-11e7-9315-8ea682da7a4b.png)

**Comment by londumas** [comment] 2017-11-08 22:12
a way to investigate this would be to use the same quasars for the CIV forest and the MGII forest.

**Comment by londumas** [comment] 2017-11-10 16:46
The last eta plot was wrong. The difference of eta from the different forests was only because I did no rebinning for the LYA, CIV, SiIV forests but rebin 2 in the MGII forest. Using the same rebining gives the basically the same results for eta across all forests.
The only difference are for Lya and Lyb. It might be linked to degeneracies between sigma_LSS and eta

![eta_lambdaobs_samebinning](https://user-images.githubusercontent.com/3166436/32668721-994060e8-c5fb-11e7-9d2f-e539e59c9f80.png)

**Comment by ngbusca** [comment] 2017-11-14 04:19
@londumas I can't confirm this last plot. I find good agreement between lya and lyb at low lambda_obs. Can you double check?

![image](https://user-images.githubusercontent.com/4727509/32762735-69356030-c8fb-11e7-920d-754302ac42f4.png)

**Comment by londumas** [comment] 2017-11-14 04:31
It is just a defintion of Lyb, what is yours ? Mine is:
```
--lambda-min 3600.0
--lambda-max 7235.0
--lambda-rest-min 800.0
--lambda-rest-max 1020.0
```

**Comment by ngbusca** [comment] 2017-11-14 04:38
I use 

`--lambda-max 4590`
`--lambda-rest-min 973`
`--zqso-max 3.5`

I wouldn't go below lambda-rest-min 973 because then you have the lyman-gamma and other forests mixed.

**Comment by londumas** [comment] 2017-11-14 04:40
I totally agree. I just did that to test.
Do you need me to compute it again ?

**Comment by ngbusca** [comment] 2017-11-14 04:41
it's not high priority, but if you confirm that there's no problem then we close the issue.

**Comment by londumas** [comment] 2017-11-14 04:42
even your plot has a problem, just look at eta for lambda>4500

**Comment by ngbusca** [comment] 2017-11-14 04:43
The last few bins contain very little statistics, I don't think that's a problem.

**Comment by londumas** [comment] 2017-11-14 06:11
Here is what I get reducing to lambdaRF = 973:
![capture d ecran de 2017-11-13 23-11-19](https://user-images.githubusercontent.com/3166436/32765507-fbed1afa-c8c7-11e7-96f0-a58705d32ae5.png)

**Comment by londumas** [comment] 2017-11-14 06:13
I agree that there seems to be no bugs anymore in picca.
But the differences between DR12Q and DR14Q for the eta(l) and var_lss(l) plots show that there are bugs in DR14Q

**Comment by ngbusca** [comment] 2017-11-14 06:17
@londumas you  are including qsos with z>3.5. We know those have a large contamination with lowz quasars in DR14Q. Is this what you are talking about?

**Comment by londumas** [comment] 2017-11-14 14:36
yes, it seems to be this.

**Closed** 2017-11-16 18:49 UTC
