### ISSUE TITLE
IO error in do_deltas

### ISSUE THREAD

**Issue by mblomqvist** [igmhub/picca#316] opened 2018-02-14 15:10 UTC
When running do_deltas for DR12Q with mode=spec the code encounters an IO error from prep_Pk1D:
```
File "/picca/py/picca/io.py", line 250, in read_from_spec
    diff = exp_diff(h,ll)
  File "/picca/py/picca/prep_Pk1D.py", line 16, in exp_diff
    llexp = file[4+iexp+icol*nexp_per_col]["loglam"][:]
  File "/anaconda/envs/python2/lib/python2.7/site-packages/fitsio/fitslib.py", line 994, in __getitem__
    raise IOError("extension not found: %s %s" % (ext,mess))
IOError: extension not found: 4 (case insensitive)
```

**Comment by londumas** [comment] 2018-02-14 15:12
@mblomqvist, could you give the input command?

**Comment by mblomqvist** [comment] 2018-02-14 15:13
Why does prep_Pk1D need to get called in a regular do_deltas analysis?

**Comment by londumas** [comment] 2018-02-14 15:13
@mblomqvist, it shouldn't. That is why I would like to see the command you send.

**Comment by mblomqvist** [comment] 2018-02-14 15:16
do_deltas.py --drq DR12Q.fits --in-dir /eboss/spectro/redux/v5_9_0/spectra/lite --out-dir /deltas/ --iter-out-prefix delta_attributes_lya_dr12_baseline --log input_lya_dr12_baseline.log --dla-vac DLA_DR12_v2.dat --zqso-min 2.05 --zqso-max 3.5 --mode spec --npix-min 20 --lambda-max 5400 --lambda-rest-min 1040 --lambda-rest-max 1200 --mask-file /picca/etc/dr14-line-sky-mask.txt

**Comment by londumas** [comment] 2018-02-14 15:24
https://github.com/igmhub/picca/blob/080339e8e24047b3560b990d2a43e314ea70572f/py/picca/io.py#L250
Indeed, the problem is in `read_from_spec`. Could you fix it @mblomqvist? We would only need to see if we are computing the pK1d or not

**Comment by mblomqvist** [comment] 2018-02-14 15:25
Well, the person who introduced the bug should fix it.

**Comment by londumas** [comment] 2018-02-14 15:34
@Cyeche, could you correct this bug introduced by adding Pk1d?

**Comment by Cyeche** [comment] 2018-02-14 16:28
Fixed in branch fix_bug_316

**Comment by londumas** [comment] 2018-02-15 11:35
fixed in PR https://github.com/igmhub/picca/pull/317

**Closed by londumas** 2018-02-15 11:35 UTC
Labels: bug

**Comment by Cyeche** [comment] 2018-02-28 19:04
Did the bug happen only with python 3?

**Comment by ngbusca** [comment] 2018-02-28 21:01
@Cyeche no, this is related to the fact that @mblomqvist had the lite version of the spec files (without the individual exposures), so prep_Pk1D crashed. But it's been fixed in master.
